config/routes.rb
Rails.application.routes.draw do
  resources :home
  get '/chat' => 'home#chat'
  get '/movement' => 'home#movement'
  get '/joined' => 'home#joined'
  devise_for :players, controllers: { sessions: "player/sessions" }
  root 'home#index'
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ActionController::Live
  include Tubesock::Hijack
  @@players = []

  def index
    @messages = Message.all.order('created_at DESC').limit(50)
    #try and get players subscribed, not yet working
    #@players = $redis.smembers('joined')
    @@players += [current_or_guest_player.email.gsub(/[^0-9A-Za-z]/, '')]
    @players = @@players
  end

def create
  @message = Message.new
  @message.content = params[:message][:content]
  @message.name = current_or_guest_player.email
  @message.save!
  return render :nothing => true
end

 def chat
    hijack do |tubesock|
      # Listen on its own thread
      redis_thread = Thread.new do
        # Needs its own redis connection to pub
        # and sub at the same time
        Redis.new.subscribe "chat" do |on|
          on.message do |channel, message|
            tubesock.send_data message
          end
        end
      end
      tubesock.onmessage do |m|
        # pub the message when we get one
        # note: this echoes through the sub above
        Redis.new.publish "chat", m
      end
      tubesock.onclose do
        # stop listening when client leaves
        redis_thread.kill
      end
    end
  end

  def joined
    hijack do |tubesock|
      # Listen on its own thread
      redis_thread = Thread.new do
        # Needs its own redis connection to pub
        # and sub at the same time
        Redis.new.subscribe "joined" do |on|
          on.message do |channel, message|
            tubesock.send_data message
          end
        end
      end
      tubesock.onmessage do |m|
        # pub the message when we get one
        # note: this echoes through the sub above
        Redis.new.publish "joined", m
      end
      tubesock.onclose do
        # stop listening when client leaves
        redis_thread.kill
      end
    end
  end

  def movement
    hijack do |tubesock|
      # Listen on its own thread
      redis_thread = Thread.new do
        # Needs its own redis connection to pub
        # and sub at the same time
        Redis.new.subscribe "movement" do |on|
          on.message do |channel, message|
            tubesock.send_data message
          end
        end
      end
      tubesock.onmessage do |m|
        # pub the message when we get one
        # note: this echoes through the sub above
        Redis.new.publish "movement", m
      end
      tubesock.onclose do
        # stop listening when client leaves
        redis_thread.kill
      end
    end
  end
end

app/controllers/player/confirmations_controller.rb
class Player::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/player/omniauth_callbacks_controller.rb
class Player::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/player/passwords_controller.rb
class Player::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/player/registrations_controller.rb
class Player::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/player/sessions_controller.rb
class Player::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
   def create
     flash[:notice] = "#{resource.email} has joined"
     super
   end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/player/unlocks_controller.rb
class Player::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #for nice notifications with toastr
  def custom_bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      puts type

      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/home/_chat.js.erb
$(function() {
  var socket;
  socket = new WebSocket("ws://" + window.location.host + "/chat");
  socket.onmessage = function(event) {
    if (event.data.length) {
      $("#chat").append("<%= current_or_guest_player.email %> : " + event.data + "<br>");
      document.getElementById('chat').scrollTop = 9999999;
    }
  };

  return $("#chatform").on("submit", function(event) {
    var $input;
    event.preventDefault();
    $input = $(this).find("#message_content");
    socket.send($input.val());
    return $input.val(null);
  });
});

app/views/home/_game.js.erb
myId = '<%= current_or_guest_player.email.gsub(/[^0-9A-Za-z]/, '') %>';

var land;

var shadow;
var tank;
var turret;
var player;
var tanksList = {};
var explosions;
var enemy;


var cursors;

var bullets;
var fireRate = 100;
var nextFire = 0;

var moveleft = "false";
var moveright = "false";
var moveup = "false";
var movedown = "false";
var shoot = "false";

//this function will handle client communication with the server
var clientSetup = function() {
		//create() is moved here to make sure nothing is created before uniq id assignation
		create();

<% @players.uniq.each do |x| %>
  spawnEnemy('<%= x %>');
<% end %>
}


var killMe = function(i) {
        console.log('KILL');
	      tanksList[i].alive = false;
	      tanksList[i].kill();
	      tanksList[i].turret.kill();
	      tanksList[i].shadow.kill();
}

var hitme = function(i) {
      tanksList[i].health -= 1;
}

var goleft = function(i) {
    tanksList[i].tank.x -= 5;
    tanksList[i].turret.x -= 5;
    tanksList[i].shadow.x -= 5;
  }
var goright = function(i) {
    tanksList[i].tank.x += 5;
    tanksList[i].turret.x += 5;
    tanksList[i].shadow.x += 5;
  }
var goup = function(i) {
  tanksList[i].tank.y -= 5;
  tanksList[i].turret.y -= 5;
  tanksList[i].shadow.y -= 5;
  }
var godown = function(i) {
  tanksList[i].tank.y += 5;
  tanksList[i].turret.y += 5;
  tanksList[i].shadow.y += 5;
  }
var shoot = function(i, playerx, playery) {
   tanksList[i].fire({x:playerx, y:playery});
  }

var width = $('#gamescreen').innerWidth() - 50;
var height = $('#gamescreen').innerHeight();

var game = new Phaser.Game(width, height, Phaser.AUTO, 'gamescreen', { preload: preload, create: clientSetup, update: update, render: render });


function preload () {

    game.load.atlas('tank', 'assets/tanks.png', 'assets/tanks.json');
    game.load.atlas('enemy', 'assets/enemy-tanks.png', 'assets/tanks.json');
    game.load.image('bullet', 'assets/bullet.png');
    game.load.image('earth', 'assets/scorched_earth.png');
    game.load.spritesheet('kaboom', 'assets/explosion.png', 64, 64, 23);
    
}

// for when new players join and leave
Tank = function (index) {
	this.cursor = {
		left:false,
		right:false,
		up:false,
		fire:false
	}

	this.input = {
		left:false,
		right:false,
		up:false,
		fire:false
	}

    var x = 0;
    var y = 0;

    this.game = game;
    this.health = 30;
    this.player = player;
    this.points = 0;
    this.bullets = game.add.group();
    this.bullets.enableBody = true;
    this.bullets.physicsBodyType = Phaser.Physics.ARCADE;
    this.bullets.createMultiple(20, 'bullet', 0, false);
    this.bullets.setAll('anchor.x', 0.5);
    this.bullets.setAll('anchor.y', 0.5);
    this.bullets.setAll('outOfBoundsKill', true);
    this.bullets.setAll('checkWorldBounds', true);	
	
	
	this.currentSpeed =0;
    this.fireRate = 500;
    this.nextFire = 0;
    this.alive = true;
    
    if (index == myId) {
      this.shadow = game.add.sprite(x, y, 'tank', 'shadow');
      this.tank = game.add.sprite(x, y, 'tank', 'tank1');
      this.turret = game.add.sprite(x, y, 'tank', 'turret');
    }
    else {
      this.shadow = game.add.sprite(x, y, 'enemy', 'shadow');
      this.tank = game.add.sprite(x, y, 'enemy', 'tank1');
      this.turret = game.add.sprite(x, y, 'enemy', 'turret');
    }


    this.shadow.anchor.set(0.5);
    this.tank.anchor.set(0.5);
    this.turret.anchor.set(0.3, 0.5);

    this.tank.id = index;
    game.physics.enable(this.tank, Phaser.Physics.ARCADE);
    this.tank.body.immovable = false;
    this.tank.body.collideWorldBounds = true;
    this.tank.body.bounce.setTo(0, 0);

    this.tank.angle = 0;

    game.physics.arcade.velocityFromRotation(this.tank.rotation, 0, this.tank.body.velocity);
};


var spawnEnemy = function(i) {
      if (i == myId) return; //this is me
        console.log('SPAWN');
        var tnk = new Tank(i);
        tanksList[i] = tnk;
}


Tank.prototype.update = function() {
	

	//cursor value is now updated by eurecaClient.exports.updateState method
	
	
    if (this.cursor.left)
    {
        this.tank.angle -= 1;
    }
    else if (this.cursor.right)
    {
        this.tank.angle += 1;
    }	
    if (this.cursor.up)
    {
        //  The speed we'll travel at
        this.currentSpeed = 300;
    }
    else
    {
        if (this.currentSpeed > 0)
        {
            this.currentSpeed -= 4;
        }
    }
    if (this.fire == true)
    {	
		  this.fire({x:this.cursor.tx, y:this.cursor.ty});
    }
	
    if (this.currentSpeed > 0)
    {
        game.physics.arcade.velocityFromRotation(this.tank.rotation, this.currentSpeed, this.tank.body.velocity);
    }	
	else
	{
		game.physics.arcade.velocityFromRotation(this.tank.rotation, 0, this.tank.body.velocity);
	}
	
    this.shadow.x = this.tank.x;
    this.shadow.y = this.tank.y;
    this.shadow.rotation = this.tank.rotation;

    this.turret.x = this.tank.x;
    this.turret.y = this.tank.y;
};


Tank.prototype.fire = function(target) {
		if (!this.alive) return;
        if (this.game.time.now > this.nextFire && this.bullets.countDead() > 0)
        {
            this.nextFire = this.game.time.now + this.fireRate;
            var bullet = this.bullets.getFirstDead();
            bullet.reset(this.turret.x, this.turret.y);

			bullet.rotation = this.game.physics.arcade.moveToObject(bullet, target, 500);
        }
}


Tank.prototype.kill = function() {
	this.alive = false;
	this.tank.kill();
	this.turret.kill();
	this.shadow.kill();
}


function create () {

    //  Resize our game world to be a 2000 x 2000 square
    game.world.setBounds(-1000, -1000, 2000, 2000);
	game.stage.disableVisibilityChange  = true;
	
    //  Our tiled scrolling background
    land = game.add.tileSprite(0, 0, 800, 600, 'earth');
    land.fixedToCamera = true;
    
	  // create our score text in the top left corner
  text = game.add.text(game.camera.x,game.camera.y, "Score: 0", {
        font: "24px Arial",
        fill: "#ff0044",
        align: "center"
    });

	player = new Tank(myId);
	tanksList[myId] = player;
	tank = player.tank;
	turret = player.turret;
	tank.x=0;
	tank.y=0;
	bullets = player.bullets;
	shadow = player.shadow;	

    //  Explosion pool
    explosions = game.add.group();

    for (var i = 0; i < 10; i++)
    {
        var explosionAnimation = explosions.create(0, 0, 'kaboom', [0], false);
        explosionAnimation.anchor.setTo(0.5, 0.5);
        explosionAnimation.animations.add('kaboom');
    }

    tank.bringToTop();
    turret.bringToTop();
    game.camera.focusOnXY(0, 0);


    game.camera.follow(tank);
    game.camera.deadzone = new Phaser.Rectangle(150, 150, 500, 300);
    game.camera.focusOnXY(0, 0);

	
}

  function update() {
  // make the score text always follow where the camera is
  text.x = game.camera.x;
  text.y = game.camera.y;
  text.setText("Health:" + tanksList[myId].health);

	player.input.tx = game.input.x+ game.camera.x;
	player.input.ty = game.input.y+ game.camera.y;

    turret.rotation = game.physics.arcade.angleToPointer(turret);	
    land.tilePosition.x = -game.camera.x;
    land.tilePosition.y = -game.camera.y;
                           
    for (var i in tanksList) {
		  if (!tanksList[i]) continue;
		  var curBullets = tanksList[i].bullets;
	  	var curTank = tanksList[i].tank;
		  for (var j in tanksList) {
			  if (!tanksList[j]) continue;
			  if (j!=i) {
				  var targetTank = tanksList[j].tank;
				  game.physics.arcade.overlap(curBullets, targetTank, bulletHitPlayer, null, this);
		  	}
			  if (tanksList[j].alive) {
				  tanksList[j].update();
			  }
		}
}
  }
                           
function bulletHitPlayer (tank, bullet) {
    bullet.kill();
    playerhit(tank.id);
}

function render () {}

app/views/home/_gamemovement.js.erb
$(function() {
  var socket;
  var playerx;
  var playery;
  socket = new WebSocket("ws://" + window.location.host + "/movement");
  socket.onmessage = function(event) {
    if (event.data.length) {
     if ( event.data.charAt( 0 ) == 'l' ) {
         goleft(event.data.substring(1));
        }
     if ( event.data.charAt( 0 ) == 'r' ) {
         goright(event.data.substring(1));
        }
     if ( event.data.charAt( 0 ) == 'u' ) {
         goup(event.data.substring(1));
        }
     if ( event.data.charAt( 0 ) == 'd' ) {
         godown(event.data.substring(1));
        }
     if ( event.data.charAt( 0 ) == 'x' ) {
         playerx = event.data.substring(1);
        }
     if ( event.data.charAt( 0 ) == 'y' ) {
         playery = event.data.substring(1);
        }
     if ( event.data.charAt( 0 ) == 's' ) {
        shoot(event.data.substring(1), playerx, playery);
        }
     if ( event.data.charAt( 0 ) == 'h' ) {
        hitme(event.data.substring(1));
        }
    }
  };

$( "#gamescreen" ).mousedown(function() {
    //  shoot
    socket.send("x"+(game.input.x+ game.camera.x));
    socket.send("y"+(game.input.y+ game.camera.y));
    socket.send("s<%= current_or_guest_player.email.gsub(/[^0-9A-Za-z]/, '')%>");
});

window.playerhit = function(i) {
  socket.send("h"+i);
};

$("body").keydown(function(e) {
  if(e.keyCode == 37) { // left
    //  Move to the left
    socket.send("l<%= current_or_guest_player.email.gsub(/[^0-9A-Za-z]/, '')%>");
  }
  else if(e.keyCode == 39) { // right
    //  Move to the right
    socket.send("r<%= current_or_guest_player.email.gsub(/[^0-9A-Za-z]/, '')%>");
  }
  else if(e.keyCode == 38) { // up
    //  Move up
    socket.send("u<%= current_or_guest_player.email.gsub(/[^0-9A-Za-z]/, '')%>");
  }
  else if(e.keyCode == 40) { // down
    //  Move down
    socket.send("d<%= current_or_guest_player.email.gsub(/[^0-9A-Za-z]/, '')%>");
  }
});
});

app/views/home/_home.js.erb
$(function() {
  var socket;
  socket = new WebSocket("ws://" + window.location.host + "/chat");
  socket.onmessage = function(event) {
    if (event.data.length) {
      switch (event.data) {
        case "left":
          movementSystem(event.data)
          break;
        case "right":
          movementSystem(event.data)
          break;
        case "up":
          movementSystem(event.data)
          break;
        case "leftend":
          movementSystem(event.data)
          break;
        case "rightend":
          movementSystem(event.data)
          break;
        case "upend":
          movementSystem(event.data)
          break;
        default:
          $("#chat").append("<%= current_or_guest_player.email %> : " + event.data + "<br>");
          document.getElementById('chat').scrollTop = 9999999;
          break;
      }
    }
  };

$("body").keydown(function(e) {
  if(e.keyCode == 37) { // left
    //  Move to the left
    socket.send("left");
  }
  else if(e.keyCode == 39) { // right
    //  Move to the right
    socket.send("right");
  }
  else if(e.keyCode == 38) { // up
    //  Move up
    socket.send("up");
  }
});

$("body").keyup(function(e) {
  if(e.keyCode == 37) { // left
    //  Move to the left
    socket.send("leftend");
  }
  else if(e.keyCode == 39) { // right
    //  Move to the right
    socket.send("rightend");
  }
  else if(e.keyCode == 38) { // up
    //  Move up
    socket.send("upend");
  }
});

  return $("#chatform").on("submit", function(event) {
    var $input;
    event.preventDefault();
    $input = $(this).find("#message_content");
    socket.send($input.val());
    return $input.val(null);
  });
});

app/views/home/_playerjoined.js.erb
$(function () {
  var socket;
  socket = new WebSocket("ws://" + window.location.host + "/joined");
  socket.onmessage = function(event) {
    if (event.data.length) {
     if ( event.data.charAt( 0 ) == 'j' ) {
      var string = event.data+' has connected';
      string = string.substring(1);
      toastr.success(string);
    }
     else if ( event.data.charAt( 0 ) == 'l' ) {
      var string = event.data+' has disconnected';
      string = string.substring(1);
      toastr.error(string);
    }
    else if (event.data.charAt(0) == 's') {
      string = event.data.substring(1);
      spawnEnemy(string);
    }
    else if (event.data.charAt(0) == 'd') {
      string = event.data.substring(1);
      killMe(string);
    }
  }
  };
    setTimeout(function(){
      socket.send('j<%= truncate(current_or_guest_player.email, length: 15) %>');
      socket.send('s<%= current_or_guest_player.email.gsub(/[^0-9A-Za-z]/, '')%>');
    },3000);

  window.onunload = window.onbeforeunload = (function(){
    socket.send('l<%= truncate(current_or_guest_player.email, length: 15) %>');
    socket.send('d<%= current_or_guest_player.email.gsub(/[^0-9A-Za-z]/, '')%>');
  });
});

app/views/home/_showmessage.html.erb
<%= @message.name %>: <%= @message.content %>
<br/>

app/views/home/index.html.erb
<div class="row">
  <div class="col-xs-9" id="gamescreen"></div>
<script>
  <%= render partial: 'game.js.erb' %>
  <%= render partial: 'gamemovement.js.erb' %>
  <%= render partial: 'chat.js.erb' %>
  <%= render partial: 'playerjoined.js.erb' %>
</script>
  <div class="col-xs-3">
    <ul id="chat">
      <% @messages.each do |x| %>
        <li><%= x.name %> : <%= x.content %></li>
      <% end %>
    </ul>
    <%= form_for :message, url: home_index_path, method: 'post', html: {id: 'chatform'}, remote: true do |f| %>
      <%= f.text_field :content %>
      <%= f.submit "Send" %>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
						<!-- Brand and toggle get grouped for better mobile display -->
						<div class="navbar-header">
								<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
										<span class="sr-only">Toggle navigation</span>
										<span class="icon-bar"></span>
										<span class="icon-bar"></span>
										<span class="icon-bar"></span>
								</button>
								<%= link_to root_url, class: "navbar-brand" do %>
                  <h3>Subspace Online</h3>
								<% end %>
						</div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<!-- Top Menu Items -->
						<ul class="nav navbar-right top-nav">
                      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <%= if current_player then current_player.email else "Guest" end %>
            <span class="caret"></span>
          </a>
            <ul class="dropdown-menu" role="menu">
            <li><a href="#">Settings</a></li>
            <li class="divider"></li>
            <li><a href="#">Sign up</a></li>
            <li class="divider"></li>
            <li><a href="#">Sign in</a></li>
          </ul>
          </li>
          </ul>
          </div>
				</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SubspaceOnline</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render partial: 'layouts/header' %>
    <% if notice or alert %>
      <%= custom_bootstrap_flash %>
    <% end %>
    <main>
    <%= yield %>
    </main>
  </body>
</html>